sonar.projectKey=EL-BID_urbanpy
sonar.projectName=urbanpy

# Source code
sonar.sources=.

# Common exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/target/**,**/*.min.js,**/vendor/**,**/__pycache__/**,**/*.pyc,**/venv/**,**/.venv/**,**/coverage/**

# SCM
sonar.scm.provider=git