sonar.projectKey=EL-BID_urbanpy
sonar.projectName=urbanpy

# Source code
sonar.sources=urbanpy
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml

# Common exclusions
sonar.exclusions=**/__pycache__/**,**/*.pyc

# SCM
sonar.scm.provider=git
