sonar.projectKey=EL-BID_urbanpy
sonar.projectName=urbanpy

# Source code
sonar.sources=urbanpy
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11,3.12,3.13,3.14

# Common exclusions
sonar.exclusions=**/__pycache__/**,**/*.pyc

# SCM
sonar.scm.provider=git
