
name: Check ref tags

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Print tags 
      run: |
        echo ${{ github.ref }}
        echo ${{ github.event_name }}
