# This workflow will build docs using Sphinx and push changes to this project gh-pages branch
# For more information see: https://github.com/ammaraskar/sphinx-action

name: Publish docs to gh-pages branch

on: 
  release:
    types: [created]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v2
      with:
        ref: 'gh-pages'
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    - name: Commit documentation changes
      run: |
        git clone https://github.com/EL-BID/urbanpy.git --branch gh-pages --single-branch gh-pages
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "claudio.rtega2701@gmail.com"
        git config --local user.name "Claudio Ortega"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        