# This workflow will build the docs using Sphinx and any errors in the build process are bubbled up as Github status checks.
# For more information see: https://github.com/ammaraskar/sphinx-action

name: Docs Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
