

name: TEST

on: push
    
jobs:
  build:
    name: TEST
    runs-on: ubuntu-latest

    steps:
    - name: SED
      run: |
        sudo apt-get install sed sed-dev
        echo "hola mundo" | sed "s/hola/mundo/"
      shell: bash

