# This workflow will:
# 1. Build docs using Sphinx 
# 2. Push changes to this project gh-pages branch

name: Update Docs

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    - name: Commit documentation changes
      run: |
        git clone https://github.com/EL-BID/urbanpy.git --branch gh-pages --single-branch gh-pages
        cp -r docs/build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "claudio.rtega2701@gmail.com"
        git config --local user.name "Claudio Ortega"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
